apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: wordpress
  namespace: tp-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
               secretKeyRef: 
                key: ROOT_PASSWORD
                name: mysecret
          - name: MYSQL_DATABASE
            value: worpress
          - name: MYSQL_USER
            value: nini 
          - name: MYSQL_PASSWORD
            valueFrom: 
               secretKeyRef: 
                key: MYSQL_PASSWORD
                name: mysecret
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-data
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: pvc

