secretGenerator:
- name: mysql-pass
  literals:
  - password=PASSWORD

resources:
  - pvc.yml
  - pvc-wordpress.yml
  - service-clusterIP.yml
  - service-nodeport.yml
  - deploy-mysql.yml
  - deploy-wordpress.yml
