apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    app: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
