apiVersion: v1
kind: Service
metadata:
  name: mysvc-clusterip
  labels:
    app: mysql
  namespace: tp-wordpress
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
