apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: tp-wordpress
  labels:
    app: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
    tier: frontend
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30008
