apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: tp-wordpress
spec:
  type: NodePort
  selector:
    name: wordpress
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30007
