apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: wordpress
  namespace: tp-wordpress
spec:
  clusterIP: None
  selector:
    app: wordpress
    tier: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
